[package]
name = "bfp-rs"
version = "0.3.0-alpha24"
edition = "2021"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[features]
inline_always = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bfp_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.2"
encoding_rs = "0.8.35"
indicatif = "0.17.11"
serde = "1.0.219"
serde_json = "1.0.140"
itertools = "0.14.0"
