from bfp_rs.retrievers import Retriever


class Get:
    """
    """

    def __add__(self, other: Get | int) -> Get: ...
    def __radd__(self, other: Get | int) -> Get: ...
    def __sub__(self, other: Get | int) -> Get: ...
    def __rsub__(self, other: Get | int) -> Get: ...
    def __mul__(self, other: Get | int) -> Get: ...
    def __rmul__(self, other: Get | int) -> Get: ...
    def __div__(self, other: Get | int) -> Get: ...
    def __rdiv__(self, other: Get | int) -> Get: ...
    def __mod__(self, other: Get | int) -> Get: ...
    def __rmod__(self, other: Get | int) -> Get: ...
    def __and__(self, other: Get | int) -> Get: ...
    def __rand__(self, other: Get | int) -> Get: ...
    def __or__(self, other: Get | int) -> Get: ...
    def __ror__(self, other: Get | int) -> Get: ...
    def __xor__(self, other: Get | int) -> Get: ...
    def __rxor__(self, other: Get | int) -> Get: ...
    def __neg__(self) -> Get: ...
    def __invert__(self) -> Get: ...

def get(*source: Retriever | int) -> Get: ...

def get_len(*source: Retriever | int) -> Get: ...
