from bfp_rs.combinators.combinator import Combinator
from bfp_rs.combinators.get import Get
from bfp_rs.retrievers import Retriever


class SetRepeatBuilder:
    """
    """

    def by(self, from_: Get) -> Combinator: ...
    def from_(self, *source: Retriever | int) -> Combinator: ...
    def from_len(self, *source: Retriever | int) -> Combinator: ...
    def to(self, target) -> Combinator: ...

def set_repeat(target: Retriever) -> SetRepeatBuilder: ...
