from bfp_rs import ByteStream, Version


class Bool:
    """
    """

    @classmethod
    def to_bytes(cls, value: bool) -> bytes: ...

    @classmethod
    def from_stream(cls, value: ByteStream, ver: Version = Version(0)) -> bool: ...

    @classmethod
    def from_file(cls, filepath: str) -> bool: ...

    @classmethod
    def from_bytes(cls, bytes_: bytes, ver: Version = Version(0)) -> bool: ...

    @classmethod
    def to_file(cls, filepath: str, value: bool): ...

class bool8(Bool): ...
class bool16(Bool): ...
class bool32(Bool): ...
class bool64(Bool): ...
class bool128(Bool): ...
