from typing import Self


class Encoding:
    """Enum for specifying different string encodings in various string related types"""
    ASCII: Self = ...
    UTF8: Self = ...
    UTF16: Self = ...
    UTF32: Self = ...
    LATIN1: Self = ...
    WINDOWS1252: Self = ...
