from bfp_rs import ByteStream, Version


class Int:
    """
    """

    @classmethod
    def to_bytes(cls, value: int) -> bytes: ...

    @classmethod
    def from_stream(cls, value: ByteStream, ver: Version = Version(0)) -> int: ...

    @classmethod
    def from_file(cls, filepath: str) -> int: ...

    @classmethod
    def from_bytes(cls, bytes_: bytes, ver: Version = Version(0)) -> int: ...

    @classmethod
    def to_file(cls, filepath: str, value: int): ...

class u8(Int): ...
class u16(Int): ...
class u32(Int): ...
class u64(Int): ...
class u128(Int): ...

class i8(Int): ...
class i16(Int): ...
class i32(Int): ...
class i64(Int): ...
class i128(Int): ...
