from bfp_rs import ByteStream, Version
from bfp_rs.types.le.encodings import Encoding


class NtStr:
    """
    """
    _0: type[NtStr]

    @classmethod
    def to_bytes(cls, value: str) -> bytes: ...

    @classmethod
    def from_stream(cls, value: ByteStream, ver: Version = Version(0)) -> str: ...

    @classmethod
    def from_file(cls, filepath: str) -> str: ...

    @classmethod
    def from_bytes(cls, bytes_: bytes, ver: Version = Version(0)) -> str: ...

    @classmethod
    def to_file(cls, filepath: str, value: str): ...

    @classmethod
    def __class_getitem__(cls, item: int | Encoding | tuple[Encoding, Encoding]) -> type: ...


class c_str(NtStr): ...
class nt_str8(NtStr): ...
class nt_str16(NtStr): ...
class nt_str32(NtStr): ...
class nt_str64(NtStr): ...
class nt_str128(NtStr): ...
