from bfp_rs import ByteStream, Version
from bfp_rs.types.le.encodings import Encoding


class Str:
    """
    """
    _0: type[Str]

    @classmethod
    def to_bytes(cls, value: str) -> bytes: ...

    @classmethod
    def from_stream(cls, value: ByteStream, ver: Version = Version(0)) -> str: ...

    @classmethod
    def from_file(cls, filepath: str) -> str: ...

    @classmethod
    def from_bytes(cls, bytes_: bytes, ver: Version = Version(0)) -> str: ...

    @classmethod
    def to_file(cls, filepath: str, value: str): ...

    @classmethod
    def __class_getitem__(cls, item: int | Encoding | tuple[Encoding, Encoding]) -> type: ...


class str8(Str): ...
class str16(Str): ...
class str32(Str): ...
class str64(Str): ...
class str128(Str): ...
