from bfp_rs import ByteStream, Version
from bfp_rs.types.le.encodings import Encoding


class StrArray:
    """
    """
    _0: type[StrArray]

    @classmethod
    def to_bytes(cls, value: list[str]) -> bytes: ...

    @classmethod
    def from_stream(cls, value: ByteStream, ver: Version = Version(0)) -> list[str]: ...

    @classmethod
    def from_file(cls, filepath: str) -> list[str]: ...

    @classmethod
    def from_bytes(cls, bytes_: bytes, ver: Version = Version(0)) -> list[str]: ...

    @classmethod
    def to_file(cls, filepath: str, value: list[str]): ...

    @classmethod
    def __class_getitem__(cls, item: int | Encoding | tuple[Encoding, Encoding]) -> type: ...


class str_array8(StrArray): ...
class str_array16(StrArray): ...
class str_array32(StrArray): ...
class str_array64(StrArray): ...
class str_array128(StrArray): ...
