class Version:
    """
    """

    def __new__(cls, *nums: int) -> Version: ...

    @classmethod
    def from_str(cls: Version, ver_str: str) -> Version: ...

    def __le__(self, other: Version) -> bool: ...
    def __ge__(self, other: Version) -> bool: ...
    def __eq__(self, other: Version) -> bool: ...
    def __ne__(self, other: Version) -> bool: ...
    def __lt__(self, other: Version) -> bool: ...
    def __gt__(self, other: Version) -> bool: ...
